{{- if not .Values.hbn.nvue_credentials_secret_name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carbide-dpu-agent.fullname" . }}-nvue-creds
  labels:
    {{- include "carbide-dpu-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.hbn.nvue_username_key }}: {{ .Values.hbn.nvue_username | b64enc }}
  {{ .Values.hbn.nvue_password_key }}: {{ .Values.hbn.nvue_password | b64enc }}
{{- end }}
