apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envFrom.pxeEnvConfig.configMapName }}
  namespace: {{ include "nico-pxe.namespace" . }}
  labels:
    {{- include "nico-pxe.labels" . | nindent 4 }}
data:
  NICO_API_HOST: {{ printf "nico-api.%s.svc.cluster.local" (include "nico-pxe.namespace" .) | quote }}
  NICO_API_PORT: {{ .Values.config.nicoApiPort | default "1079" | quote }}
  {{- range $key, $value := .Values.config.extraEnvData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
