apiVersion: v1
kind: Service
metadata:
  name: nico-pxe-metrics
  namespace: {{ include "nico-pxe.namespace" . }}
  labels:
    {{- include "nico-pxe.labels" . | nindent 4 }}
    app: nico-pxe
    app.kubernetes.io/metrics: nico-pxe
spec:
  selector:
    {{- include "nico-pxe.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.service.port }}
