{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nico-pxe-metrics
  namespace: {{ include "nico-pxe.namespace" . }}
  labels:
    {{- include "nico-pxe.labels" . | nindent 4 }}
    app: nico-pxe
    prometheus: nico-monitoring
spec:
  {{- include "nico-pxe.serviceMonitorSpec" (dict "name" "nico-pxe" "port" "http" "monitor" .Values.serviceMonitor "namespace" "nico-system") | nindent 2 }}
{{- end }}
