apiVersion: v1
kind: Service
metadata:
  name: nico-api-metrics
  namespace: {{ include "nico-api.namespace" . }}
  labels:
    {{- include "nico-api.labels" . | nindent 4 }}
    app: nico-api
    app.kubernetes.io/metrics: nico-api
spec:
  selector:
    {{- include "nico-api.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.metrics.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.service.metrics.port }}
