apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "carbide-nginx.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- if .Values.configFiles.nginxConf }}
    {{- .Values.configFiles.nginxConf | nindent 4 }}
    {{- else }}
    {{- .Files.Get "files/nginx.conf" | nindent 4 }}
    {{- end }}
