apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "carbide-nginx.labels" . | nindent 4 }}
automountServiceAccountToken: true
