{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nico-ssh-console-rs-metrics
  namespace: {{ include "nico-ssh-console-rs.namespace" . }}
  labels:
    {{- include "nico-ssh-console-rs.labels" . | nindent 4 }}
    app: nico-ssh-console-rs
    prometheus: nico-monitoring
spec:
  {{- include "nico-ssh-console-rs.serviceMonitorSpec" (dict "name" "nico-ssh-console-rs" "port" "http" "monitor" .Values.serviceMonitor "namespace" "nico-system") | nindent 2 }}
{{- end }}
